
language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

install: travis_retry composer install

script: composer install

after_success:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
